### ISSUE TITLE
Document how to integrate Globus Connect with a given endpoint

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/globus_client#25]
Do what it says above

**Comment by mjgiarlo** [comment]
Mike will test on Linux w/ non-admin user.

**Comment by lwrubel** [comment]
To use Globus Personal Connect to see a folder set up in the test endpoint:

1) Open up Personal Connect. If it's not open, use the Globus icon's dropdown options to select Web: File Transfer. 
![Dropdown-globus-client](https://user-images.githubusercontent.com/1619369/203128910-30e94c5e-4c1b-404c-8a0c-e028e530acc8.png)

2) Click the Collections link in the left sidebar and then search for "h2 test endpoint" 
![collection-search](https://user-images.githubusercontent.com/1619369/203129111-2a360f01-a93b-4283-a2f0-602ebbc0a090.png)

3) After clicking on the h2 test endpoint collection link, Open in File Manager
![File-Manager-link](https://user-images.githubusercontent.com/1619369/203129191-4509a3b8-634f-4302-bd31-ffa41bad261c.png)

4) The File Manager view allows you to browse to the directory set up for you as a user via Globus. If you are an admin, you will see all files.
![File-manager-browse](https://user-images.githubusercontent.com/1619369/203129832-61824464-39e7-46ff-b626-226acba2f448.png)

**Comment by lwrubel** [comment]
@mjgiarlo, this is ready for you to walk through with Globus Personal Connect on your computer.

**Comment by aaron-collier** [comment]
@lwrubel I'm unable to get past "open in file manager" I get permission denied

**Comment by lwrubel** [comment]
@aaron-collier I believe this is because you don't have any folders set with permissions for you to see them. So since there is nothing to show, it does not allow you to browse files. 

I gave you read/write access to the folder `/uploads/amcollie/work123/version1/` to test this theory. Could you try going into Globus Personal Connect again and seeing what shows up now?

**Comment by aaron-collier** [comment]
@lwrubel perfect! that worked!

**Comment by mjgiarlo** [comment]
Awesome! Closing.
