### ISSUE TITLE
Resolve operations-related questions

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/globus_client#37]
1. Is the storage on the DOR workspace sufficient in QA, stage, and prod for us to start working on Globus in earnest?
2. The current QA Globus endpoint is working out well. Can you also create new Globus endpoints for stage and prod?
3. Can we (re-)name these endpoints to  "SDR qa|stage|prod endpoint"? (Since H2 will not directly write or read files from them.)
4. Can we move the Globus mounts from dsa-qa and -stage to sdr-api-qa?

cc: @rsmith11

**Comment by rsmith11** [comment]
1. The /dor mount on qa and stage has 1TB free, and the prod /dor mount has 20TB free
2.  I can make new mounts.  Just to document it here, our Globus environment has no qa/stage environment, only a single production server.  I'll be making the new qa/stage mounts on the production server.
3. no problem there. 
4. no problem there as well.  

I'll get started working on these this week.  Do you want the same user created in testing to be used for these new endpoints?

**Comment by mjgiarlo** [comment]
@rsmith11 💬 
> 1. The /dor mount on qa and stage has 1TB free, and the prod /dor mount has 20TB free

OK, sounds like we're good to go, then.

> 2. I can make new mounts.  Just to document it here, our Globus environment has no qa/stage environment, only a single production server.  I'll be making the new qa/stage mounts on the production server.

Sounds good, Rob.

> 3. no problem there.
> 4. no problem there as well.

🍻 
 
> I'll get started working on these this week. Do you want the same user created in testing to be used for these new endpoints?

I pinged you on Slack about this.

**Comment by mjgiarlo** [comment]
@rsmith11 Thanks, and feel free to close this issue when you are done (or just ping me, either way)

**Comment by rsmith11** [comment]
The new shared endpoints are created for each environment, and each environments' client_id, secret, and endpoint_uuid is stored in vault at puppet/application/sdr/globus/.  Working on changing the mounts next.

**Comment by mjgiarlo** [comment]
This is now done.
