### ISSUE TITLE
Return a list of files given a path

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/globus_client#49]
Building on prior work around creating directories and returning file counts and sizes, add a new public API method that uses the `Endpoint` to retrieve a list of files given a path argument (see how `Endpoint#mkdir` uses the path).

**Comment by lwrubel** [comment]
Note that Globus does not paginate directory listing responses by default. There is a max of 100,000 records returned. See [Globus docs for page param](https://docs.globus.org/api/transfer/file_operations/#directory_listing_query_parameters). Pagination can be requested if needed.
