### ISSUE TITLE
Create method for assinging permissions to folder for specific user

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/globus_client#8]
some sample code may exist

**Comment by lwrubel** [comment]
@peetucket  while I'm working on this, it would make sense to update what the folder structure is. Currently, the gem creates a folder structure that looks like:

`<sunetid>/<workid>/version<num>/`

I remember us discussing simplifying this--did we resolve that question? I can't find a ticket and it's not part of the mockups.  I think it needs @amyehodge's input.

**Comment by amyehodge** [comment]
@lwrubel @peetucket My last recollection was a discussion I had with Peter where we ended up deciding that we should keep this. I can envision a user initiating more than one Globus deposit at a time or possibly versioning an item before we clean up the data in Globus, we I think we should keep that full structure as you have it above.
