### ISSUE TITLE
Create method for getting the number of files and file sizes from a given endpoint

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/globus_client#9]
Given a globus endpoint, fetch the total number of files and filesize for each.  This will allow us to display this information to users in H2.

**Comment by mjgiarlo** [comment]
I poked at this a bit and got as far as installing Globus locally, at which point I realized I don't grok how my own Globus account connects to the Globus stuff we've already set up. And in the interest of staying off the critical path, I unassigned. :)

**Comment by mjgiarlo** [comment]
Depends on #25
